// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8VWpZi8BHaHIrrj2i1N7NqDZvI9QMXF4',
    appId: '1:230624573968:web:a72aa955a2840c38c06895',
    messagingSenderId: '230624573968',
    projectId: 'pnotes-pilot-project-dhrubi',
    authDomain: 'pnotes-pilot-project-dhrubi.firebaseapp.com',
    storageBucket: 'pnotes-pilot-project-dhrubi.appspot.com',
    measurementId: 'G-X08YB4D54M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXCJbpRmGak1bCrNOSvTPN4-6SdIQ6wxs',
    appId: '1:230624573968:android:45db70ab9802a46dc06895',
    messagingSenderId: '230624573968',
    projectId: 'pnotes-pilot-project-dhrubi',
    storageBucket: 'pnotes-pilot-project-dhrubi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrLVgtwRBhiDuqKRc-TD8Y2qgLmB-OgDg',
    appId: '1:230624573968:ios:29ba76fa134405aec06895',
    messagingSenderId: '230624573968',
    projectId: 'pnotes-pilot-project-dhrubi',
    storageBucket: 'pnotes-pilot-project-dhrubi.appspot.com',
    iosBundleId: 'com.dhrubi.pnotes',
  );
}
